
package com.trainig.statproducer;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-27T16:12:07.851+02:00
 * Generated source version: 2.7.6
 * 
 */
public final class StatProducer_StatProducerSOAPPort1_Client {

    private static final QName SERVICE_NAME = new QName("http://www.trainig.com/StatProducer/", "StatProducerSOAPPorts");

    private StatProducer_StatProducerSOAPPort1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StatProducerSOAPPorts.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StatProducerSOAPPorts ss = new StatProducerSOAPPorts(wsdlURL, SERVICE_NAME);
        StatProducer port = ss.getStatProducerSOAPPort1();  
        
        {
        System.out.println("Invoking getStatistics...");
        java.lang.String _getStatistics_param = "";
        java.lang.String _getStatistics_replyto = "";
        port.getStatistics(_getStatistics_param, _getStatistics_replyto);


        }

        System.exit(0);
    }

}
