package com.trainig.statproducer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-27T16:12:07.901+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "StatProducerSOAPPorts", 
                  wsdlLocation = "file:/C:/zero/REPOS/zero-web-services/statConsumer/src/main/resources/StatProducer.wsdl",
                  targetNamespace = "http://www.trainig.com/StatProducer/") 
public class StatProducerSOAPPorts extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.trainig.com/StatProducer/", "StatProducerSOAPPorts");
    public final static QName StatProducerSOAPPort1 = new QName("http://www.trainig.com/StatProducer/", "StatProducerSOAPPort1");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/zero/REPOS/zero-web-services/statConsumer/src/main/resources/StatProducer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StatProducerSOAPPorts.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/zero/REPOS/zero-web-services/statConsumer/src/main/resources/StatProducer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StatProducerSOAPPorts(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StatProducerSOAPPorts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatProducerSOAPPorts() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatProducerSOAPPorts(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatProducerSOAPPorts(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatProducerSOAPPorts(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns StatProducer
     */
    @WebEndpoint(name = "StatProducerSOAPPort1")
    public StatProducer getStatProducerSOAPPort1() {
        return super.getPort(StatProducerSOAPPort1, StatProducer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatProducer
     */
    @WebEndpoint(name = "StatProducerSOAPPort1")
    public StatProducer getStatProducerSOAPPort1(WebServiceFeature... features) {
        return super.getPort(StatProducerSOAPPort1, StatProducer.class, features);
    }

}
