
package com.foo.bizservice;

import javax.xml.ws.Endpoint;

import training.webservices.serviceImpl.BizServiceImpl;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-16T22:43:25.221+02:00
 * Generated source version: 2.7.6
 * 
 */
 
public class BizService_BizServiceSOAP_Server{

    protected BizService_BizServiceSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BizServiceImpl();
        String address = "http://localhost:8080/bizService/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new BizService_BizServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
