
package com.foo.bizservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-16T22:43:25.182+02:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "invalidQty", targetNamespace = "http://www.foo.com/bizService/")
public class QueryInvalidQty extends Exception {
    
    private int invalidQty;

    public QueryInvalidQty() {
        super();
    }
    
    public QueryInvalidQty(String message) {
        super(message);
    }
    
    public QueryInvalidQty(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryInvalidQty(String message, int invalidQty) {
        super(message);
        this.invalidQty = invalidQty;
    }

    public QueryInvalidQty(String message, int invalidQty, Throwable cause) {
        super(message, cause);
        this.invalidQty = invalidQty;
    }

    public int getFaultInfo() {
        return this.invalidQty;
    }
}
