
package com.foo.bizservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-16T22:43:25.128+02:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "invalidProductId", targetNamespace = "http://www.foo.com/bizService/")
public class QueryInvalidProductId extends Exception {
    
    private java.lang.String invalidProductId;

    public QueryInvalidProductId() {
        super();
    }
    
    public QueryInvalidProductId(String message) {
        super(message);
    }
    
    public QueryInvalidProductId(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryInvalidProductId(String message, java.lang.String invalidProductId) {
        super(message);
        this.invalidProductId = invalidProductId;
    }

    public QueryInvalidProductId(String message, java.lang.String invalidProductId, Throwable cause) {
        super(message, cause);
        this.invalidProductId = invalidProductId;
    }

    public java.lang.String getFaultInfo() {
        return this.invalidProductId;
    }
}
