package com.ttdev.statservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-17T15:58:35.534+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "StatServicePorts", 
                  wsdlLocation = "file:/C:/zero/REPOS/zero-web-services/statService/src/main/resources/statService.wsdl",
                  targetNamespace = "http://ttdev.com/StatService/") 
public class StatServicePorts extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ttdev.com/StatService/", "StatServicePorts");
    public final static QName StatServiceSOAPPort1 = new QName("http://ttdev.com/StatService/", "StatServiceSOAPPort1");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/zero/REPOS/zero-web-services/statService/src/main/resources/statService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StatServicePorts.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/zero/REPOS/zero-web-services/statService/src/main/resources/statService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StatServicePorts(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StatServicePorts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatServicePorts() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatServicePorts(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatServicePorts(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatServicePorts(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns StatService
     */
    @WebEndpoint(name = "StatServiceSOAPPort1")
    public StatService getStatServiceSOAPPort1() {
        return super.getPort(StatServiceSOAPPort1, StatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatService
     */
    @WebEndpoint(name = "StatServiceSOAPPort1")
    public StatService getStatServiceSOAPPort1(WebServiceFeature... features) {
        return super.getPort(StatServiceSOAPPort1, StatService.class, features);
    }

}
