
package com.ttdev.statservice;

import javax.xml.ws.Endpoint;

import com.ttdev.statservice.impl.StatServiceImpl;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-17T15:58:35.531+02:00
 * Generated source version: 2.7.6
 * 
 */
 
public class StatService_StatServiceSOAPPort1_Server{

    protected StatService_StatServiceSOAPPort1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new StatServiceImpl();
        String address = "http://localhost:8080/statService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new StatService_StatServiceSOAPPort1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
