package com.ttdev.statservice;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 2.7.6 2013-09-17T15:58:35.504+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://ttdev.com/StatService/", name = "StatService")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatService {

	@WebMethod(operationName = "getStatistics")
	public Response<java.lang.String> getStatisticsAsync(
			@WebParam(partName = "parameters", name = "getStatistics", targetNamespace = "http://ttdev.com/StatService/") java.lang.String parameters);

	@WebMethod(operationName = "getStatistics")
	public Future<?> getStatisticsAsync(
			@WebParam(partName = "parameters", name = "getStatistics", targetNamespace = "http://ttdev.com/StatService/") java.lang.String parameters,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<java.lang.String> asyncHandler);

	@WebResult(name = "getStatisticsResponse", targetNamespace = "http://ttdev.com/StatService/", partName = "parameters")
	@WebMethod(action = "http://ttdev.com/StatService/getStatistics")
	public java.lang.String getStatistics(
			@WebParam(partName = "parameters", name = "getStatistics", targetNamespace = "http://ttdev.com/StatService/") java.lang.String parameters);
}
