//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.23 at 10:06:34 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ttdev/BookService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ttdev.bookservice;
