package com.trainig.statproducer;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-19T17:05:06.832+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.trainig.com/StatProducer/", name = "StatProducer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatProducer {

    @Oneway
    @WebMethod(action = "http://www.trainig.com/StatProducer/getStatistics")
    public void getStatistics(
        @WebParam(partName = "parameters", name = "getStatistics", targetNamespace = "http://www.trainig.com/StatProducer/")
        java.lang.String parameters
    );
}
