
package com.training.statconsumer;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-20T15:45:21.512+02:00
 * Generated source version: 2.7.6
 * 
 */
 
public class StatConsumer_StatConsumerSOAPPort1_Server{

    protected StatConsumer_StatConsumerSOAPPort1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
//        Object implementor = new StatConsumerImpl();
        String address = "http://localhost:8081/statConsumer/port1";
//        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new StatConsumer_StatConsumerSOAPPort1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
