package com.training.statconsumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-20T15:45:21.514+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "StatConsumerPorts", 
                  wsdlLocation = "file:/C:/zero/WORKSPACES/ZERO-WEB-SERVICES/statConsumer/src/main/resources/StatConsumer.wsdl",
                  targetNamespace = "http://www.training.com/StatConsumer/") 
public class StatConsumerPorts extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.training.com/StatConsumer/", "StatConsumerPorts");
    public final static QName StatConsumerSOAPPort1 = new QName("http://www.training.com/StatConsumer/", "StatConsumerSOAPPort1");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/zero/WORKSPACES/ZERO-WEB-SERVICES/statConsumer/src/main/resources/StatConsumer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StatConsumerPorts.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/zero/WORKSPACES/ZERO-WEB-SERVICES/statConsumer/src/main/resources/StatConsumer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StatConsumerPorts(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StatConsumerPorts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatConsumerPorts() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatConsumerPorts(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatConsumerPorts(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StatConsumerPorts(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns StatConsumer
     */
    @WebEndpoint(name = "StatConsumerSOAPPort1")
    public StatConsumer getStatConsumerSOAPPort1() {
        return super.getPort(StatConsumerSOAPPort1, StatConsumer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatConsumer
     */
    @WebEndpoint(name = "StatConsumerSOAPPort1")
    public StatConsumer getStatConsumerSOAPPort1(WebServiceFeature... features) {
        return super.getPort(StatConsumerSOAPPort1, StatConsumer.class, features);
    }

}
