package com.training.statconsumer;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-20T15:45:43.488+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.training.com/StatConsumer/", name = "StatConsumer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatConsumer {

    @Oneway
    @WebMethod(action = "http://www.training.com/StatConsumer/putStatistics")
    public void putStatistics(
        @WebParam(partName = "parameters", name = "putStatistics", targetNamespace = "http://www.training.com/StatConsumer/")
        java.lang.String parameters
    );
}
