<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.trainig.com/StatProducer/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="StatProducer"
	targetNamespace="http://www.trainig.com/StatProducer/">

	<wsdl:types>
		<xsd:schema targetNamespace="http://www.trainig.com/StatProducer/">
			<xsd:element name="getStatistics" type="xsd:string">
			</xsd:element>
		</xsd:schema>
	</wsdl:types>


	<wsdl:message name="getStatisticsRequest">
		<wsdl:part element="tns:getStatistics" name="parameters" />
	</wsdl:message>


	<wsdl:portType name="StatProducer">
		<wsdl:operation name="getStatistics">
			<wsdl:input message="tns:getStatisticsRequest" />
		</wsdl:operation>
	</wsdl:portType>


	<wsdl:binding name="StatProducerSOAP" type="tns:StatProducer">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getStatistics">
			<soap:operation soapAction="http://www.trainig.com/StatProducer/getStatistics" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>


	<wsdl:service name="StatProducerSOAPPorts">
		<wsdl:port binding="tns:StatProducerSOAP" name="StatProducerSOAPPort1">
			<soap:address location="http://localhost:8080/statProducer/port1" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
