package com.foo.bizservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-17T11:50:42.925+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.foo.com/bizService/", name = "bizService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BizService {

    @WebResult(name = "queryResponse", targetNamespace = "http://www.foo.com/bizService/", partName = "parameters")
    @WebMethod(action = "http://www.foo.com/bizService/query")
    public QueryResponseComplexType query(
        @WebParam(partName = "parameters", name = "productQuery", targetNamespace = "http://www.foo.com/bizService/")
        ProductQueryComplexType parameters
    );
}
