
package com.foo.bizservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-17T11:50:42.878+02:00
 * Generated source version: 2.7.6
 * 
 */
public final class BizService_BizServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.foo.com/bizService/", "bizService");

    private BizService_BizServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BizService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BizService_Service ss = new BizService_Service(wsdlURL, SERVICE_NAME);
        BizService port = ss.getBizServiceSOAP();  
        
        {
        System.out.println("Invoking query...");
        com.foo.bizservice.ProductQueryComplexType _query_parameters = null;
        com.foo.bizservice.QueryResponseComplexType _query__return = port.query(_query_parameters);
        System.out.println("query.result=" + _query__return);


        }

        System.exit(0);
    }

}
