package com.foo.bizservicetwo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-16T16:46:13.156+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.foo.com/bizServiceTwo/", name = "bizServiceTwo")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BizServiceTwo {

    @WebResult(name = "queryResponse", targetNamespace = "http://www.foo.com/bizServiceTwo/", partName = "parameters")
    @WebMethod(action = "http://www.foo.com/bizServiceTwo/query")
    public QueryResponseComplexType query(
        @WebParam(partName = "parameters", name = "productQuery", targetNamespace = "http://www.foo.com/bizServiceTwo/")
        ProductQueryComplexType parameters
    );
}
