package com.foo.bizservicetwo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-16T16:46:13.164+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "bizServiceTwo", 
                  wsdlLocation = "file:/C:/zero/REPOS/zero-web-services/bizService/src/main/resources/bizServiceTwo.wsdl",
                  targetNamespace = "http://www.foo.com/bizServiceTwo/") 
public class BizServiceTwo_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.foo.com/bizServiceTwo/", "bizServiceTwo");
    public final static QName BizServiceTwoSOAP = new QName("http://www.foo.com/bizServiceTwo/", "bizServiceTwoSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/zero/REPOS/zero-web-services/bizService/src/main/resources/bizServiceTwo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BizServiceTwo_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/zero/REPOS/zero-web-services/bizService/src/main/resources/bizServiceTwo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BizServiceTwo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BizServiceTwo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BizServiceTwo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BizServiceTwo_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BizServiceTwo_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BizServiceTwo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BizServiceTwo
     */
    @WebEndpoint(name = "bizServiceTwoSOAP")
    public BizServiceTwo getBizServiceTwoSOAP() {
        return super.getPort(BizServiceTwoSOAP, BizServiceTwo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BizServiceTwo
     */
    @WebEndpoint(name = "bizServiceTwoSOAP")
    public BizServiceTwo getBizServiceTwoSOAP(WebServiceFeature... features) {
        return super.getPort(BizServiceTwoSOAP, BizServiceTwo.class, features);
    }

}
