
package com.foo.bizservicetwo;

import javax.xml.ws.Endpoint;

import training.webservices.serviceImpl.BizServiceTwoImpl;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-16T16:46:13.162+02:00
 * Generated source version: 2.7.6
 * 
 */
 
public class BizServiceTwo_BizServiceTwoSOAP_Server{

    protected BizServiceTwo_BizServiceTwoSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BizServiceTwoImpl();
        String address = "http://www.foo.com/bizService/query";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new BizServiceTwo_BizServiceTwoSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
